version: '3'
services:  
  db:
    image: mysql
    ports:
      - "3305:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=doremon
    volumes:
      - mysql-data:/var/lib/mysql

  golang-rest-api:
    build: .
    ports: 
      - "8080:8080"
    volumes: 
      - ".:/app"
    depends_on: 
      - db
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=doremon
      - MYSQL_HOST=db
    links:
      - "db:database"

volumes:
  mysql-data: