version: '3'
services:  
  db:
    image: mysql
    ports:
      - "3305:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - mysql-data:/var/lib/mysql

  golang-rest-api:
    build: .
    ports: 
      - "8080:8080"
    volumes: 
      - ".:/app"
    depends_on: 
      - db
    env_file:
      - .env
    links:
      - "db:database"

volumes:
  mysql-data: